### PR TITLE
Shorten commands

### LINKED ISSUE #101: Shorten command keywords

### PR DESCRIPTION
**Pull request by ivanchongzhien**
### Command changes:

**_Dashboard commands:_**
delete -> del
modules -> mods

**_In module commands_**
teachers -> tch
lessons -> lsn

add cheat-sheet -> add cs
delete cheat-sheet -> del cs
edit cheat-sheet -> edit cs
cheat-sheet -> cs

add lesson -> add lsn
edit lesson -> edit lsn
delete lesson -> del lsn

delete task -> del task

Resolves #101

### CODE REVIEW

**Comment by ivanchongzhien** [comment]
Do let me know if you disagree or have other suggestions for the command names. I will update in the UG tomorrow and push to this same PR. Thanks guys!

**Review by H-horizon — APPROVED** [review]
LGTM

**Comment by aliciatay-zls** [comment]
> Do let me know if you disagree or have other suggestions for the command names. I will update in the UG tomorrow and push to this same PR. Thanks guys!

Maybe lessons -> lsns ? Looks good otherwise!

**Comment by ivanchongzhien** [comment]
> Looks really good, nice! Only one thing, maybe can use "tsk" for the task commands? Not so much to save letters but more to standardise so that all the commands are easier to remember for the user.

Hm you have a point there about consistency, we did consider it at first but then we realized that we have quite a few other 4 letter commands (exit, list, close - 5 letter) which did not need to be shortened as they were already short enough, plus keeping the full word where possible might improve the understandability?

**Pull request merged**
